# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
apt_packages:
  - "curl"
  - "clang-7"
  - "clang-format-7"
  - "make"
  - "ninja-build"
  - "shellcheck"
  - "gcc"
  - "g++"
  - "gdb"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
  - "libcurl4-openssl-dev"

apt_arm_packages:
  - "gcc-aarch64-linux-gnu"
  - "g++-aarch64-linux-gnu"
  - "libc6-dev:arm64"
  - "libssl-dev:arm64"
