name: Unit Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: edgsys/oetools-full-18.04
    steps:

    - uses: actions/checkout@v2

    - name: Setup directories
      run: |
        mkdir build
        mkdir build_zip

    - name: CMake and Ninja
      run: |
        cmake -GNinja ..
        ninja
      working-directory: build

    - name: CTest
      run: |
        OE_SIMULATION=1 ctest --output-on-failure
      working-directory: build

    - name: Zip Build
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./build_zip/build.zip build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build_zip
        path: build_zip
